-- GENERATED by C->Haskell Compiler, version 0.16.2 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "ArithInterface.chs" #-}{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE TypeSynonymInstances #-}
module ArithInterface where


import Text.Antlrc.Lexer
{-# LINE 7 "ArithInterface.chs" #-}

import Prelude hiding (LT, EQ, GT)
import C2HS
import Foreign.Ptr
import System.IO.Unsafe
import Foreign.C
import Control.Monad
import Control.Applicative ((<$>))

data ArithTokens = LT
                 | STAR
                 | LSQUARE
                 | LCURLYBAR
                 | DQUOTE
                 | BARRSQUARE
                 | BARGT
                 | TRIANGLE
                 | LPAREN
                 | IF
                 | UCID
                 | COLONHASH
                 | ML_COMMENT
                 | VBAR
                 | RPAREN
                 | SLASH
                 | THEN
                 | COLONEQ
                 | COMMA
                 | DARROW
                 | SUCC
                 | LEFTARROW
                 | DIGIT
                 | APOSTROPHE
                 | EQ
                 | DOT
                 | FRACTIONAL_CONSTANT
                 | INTV
                 | EQEQ
                 | DDARROW
                 | PRED
                 | ELSE
                 | HASH
                 | LSQUAREBAR
                 | LCURLY
                 | BANG
                 | RSQUARE
                 | TRUE
                 | SEMI
                 | BARRCURLY
                 | COLON
                 | COLONCOLON
                 | LCID
                 | WS
                 | DIGIT_SEQUENCE
                 | USCORE
                 | RCURLY
                 | ARROW
                 | GT
                 | FALSE
                 | NONZERO_DIGIT
                 | FLOATV
                 | ISZERO
                 deriving (Eq,Show)
instance Enum ArithTokens where
  fromEnum LT = 37
  fromEnum STAR = 43
  fromEnum LSQUARE = 35
  fromEnum LCURLYBAR = 32
  fromEnum DQUOTE = 13
  fromEnum BARRSQUARE = 18
  fromEnum BARGT = 16
  fromEnum TRIANGLE = 44
  fromEnum LPAREN = 34
  fromEnum IF = 4
  fromEnum UCID = 49
  fromEnum COLONHASH = 22
  fromEnum ML_COMMENT = 56
  fromEnum VBAR = 46
  fromEnum RPAREN = 39
  fromEnum SLASH = 42
  fromEnum THEN = 5
  fromEnum COLONEQ = 21
  fromEnum COMMA = 23
  fromEnum DARROW = 24
  fromEnum SUCC = 9
  fromEnum LEFTARROW = 33
  fromEnum DIGIT = 48
  fromEnum APOSTROPHE = 12
  fromEnum EQ = 27
  fromEnum DOT = 26
  fromEnum FRACTIONAL_CONSTANT = 52
  fromEnum INTV = 47
  fromEnum EQEQ = 28
  fromEnum DDARROW = 25
  fromEnum PRED = 10
  fromEnum ELSE = 6
  fromEnum HASH = 30
  fromEnum LSQUAREBAR = 36
  fromEnum LCURLY = 31
  fromEnum BANG = 15
  fromEnum RSQUARE = 40
  fromEnum TRUE = 7
  fromEnum SEMI = 41
  fromEnum BARRCURLY = 17
  fromEnum COLON = 19
  fromEnum COLONCOLON = 20
  fromEnum LCID = 50
  fromEnum WS = 55
  fromEnum DIGIT_SEQUENCE = 54
  fromEnum USCORE = 45
  fromEnum RCURLY = 38
  fromEnum ARROW = 14
  fromEnum GT = 29
  fromEnum FALSE = 8
  fromEnum NONZERO_DIGIT = 51
  fromEnum FLOATV = 53
  fromEnum ISZERO = 11

  toEnum 37 = LT
  toEnum 43 = STAR
  toEnum 35 = LSQUARE
  toEnum 32 = LCURLYBAR
  toEnum 13 = DQUOTE
  toEnum 18 = BARRSQUARE
  toEnum 16 = BARGT
  toEnum 44 = TRIANGLE
  toEnum 34 = LPAREN
  toEnum 4 = IF
  toEnum 49 = UCID
  toEnum 22 = COLONHASH
  toEnum 56 = ML_COMMENT
  toEnum 46 = VBAR
  toEnum 39 = RPAREN
  toEnum 42 = SLASH
  toEnum 5 = THEN
  toEnum 21 = COLONEQ
  toEnum 23 = COMMA
  toEnum 24 = DARROW
  toEnum 9 = SUCC
  toEnum 33 = LEFTARROW
  toEnum 48 = DIGIT
  toEnum 12 = APOSTROPHE
  toEnum 27 = EQ
  toEnum 26 = DOT
  toEnum 52 = FRACTIONAL_CONSTANT
  toEnum 47 = INTV
  toEnum 28 = EQEQ
  toEnum 25 = DDARROW
  toEnum 10 = PRED
  toEnum 6 = ELSE
  toEnum 30 = HASH
  toEnum 36 = LSQUAREBAR
  toEnum 31 = LCURLY
  toEnum 15 = BANG
  toEnum 40 = RSQUARE
  toEnum 7 = TRUE
  toEnum 41 = SEMI
  toEnum 17 = BARRCURLY
  toEnum 19 = COLON
  toEnum 20 = COLONCOLON
  toEnum 50 = LCID
  toEnum 55 = WS
  toEnum 54 = DIGIT_SEQUENCE
  toEnum 45 = USCORE
  toEnum 38 = RCURLY
  toEnum 14 = ARROW
  toEnum 29 = GT
  toEnum 8 = FALSE
  toEnum 51 = NONZERO_DIGIT
  toEnum 53 = FLOATV
  toEnum 11 = ISZERO
  toEnum unmatched = error ("ArithTokens.toEnum: Cannot match " ++ show unmatched)

{-# LINE 17 "ArithInterface.chs" #-}


