-- GENERATED by C->Haskell Compiler, version 0.16.2 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "FullUntypedInterface.chs" #-}-- Copyright (c)2010-2011, Mark Wright.  All rights reserved.

{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE TypeSynonymInstances #-}
module FullUntypedInterface where


import Text.Antlrc.Lexer
{-# LINE 9 "FullUntypedInterface.chs" #-}

import Prelude hiding (LT, EQ, GT)
import C2HS
import Foreign.Ptr
import System.IO.Unsafe
import Foreign.C
import Control.Monad
import Control.Applicative ((<$>))

data FullUntypedTokens = UNIVERSAL_CHARACTER_NAME
                       | S_CHAR_SEQUENCE
                       | LT
                       | STAR
                       | LSQUARE
                       | S_CHAR
                       | OCTAL_ESCAPE_SEQUENCE
                       | STRINGV
                       | LCURLYBAR
                       | DQUOTE
                       | HEXADECIMAL_DIGIT
                       | TIMESFLOAT
                       | BARRSQUARE
                       | BARGT
                       | TRIANGLE
                       | LPAREN
                       | IF
                       | SIMLE_ESCAPE_SEQUENCE
                       | UCID
                       | COLONHASH
                       | ML_COMMENT
                       | ESCAPE_SEQUENCE
                       | VBAR
                       | RPAREN
                       | SLASH
                       | IN
                       | THEN
                       | COLONEQ
                       | COMMA
                       | HEXADECIMAL_ESCAPE_SEQUENCE
                       | DARROW
                       | SUCC
                       | LEFTARROW
                       | DIGIT
                       | APOSTROPHE
                       | LAMBDA
                       | EQ
                       | DOT
                       | FRACTIONAL_CONSTANT
                       | INTV
                       | EQEQ
                       | DDARROW
                       | PRED
                       | ELSE
                       | HASH
                       | LSQUAREBAR
                       | LCURLY
                       | BANG
                       | RSQUARE
                       | SEMI
                       | TRUE
                       | BARRCURLY
                       | COLON
                       | COLONCOLON
                       | LCID
                       | WS
                       | DIGIT_SEQUENCE
                       | USCORE
                       | RCURLY
                       | ARROW
                       | GT
                       | FALSE
                       | NONZERO_DIGIT
                       | LET
                       | FLOATV
                       | ISZERO
                       deriving (Eq,Show)
instance Enum FullUntypedTokens where
  fromEnum UNIVERSAL_CHARACTER_NAME = 61
  fromEnum S_CHAR_SEQUENCE = 62
  fromEnum LT = 41
  fromEnum STAR = 47
  fromEnum LSQUARE = 39
  fromEnum S_CHAR = 63
  fromEnum OCTAL_ESCAPE_SEQUENCE = 66
  fromEnum STRINGV = 54
  fromEnum LCURLYBAR = 36
  fromEnum DQUOTE = 17
  fromEnum HEXADECIMAL_DIGIT = 56
  fromEnum TIMESFLOAT = 10
  fromEnum BARRSQUARE = 22
  fromEnum BARGT = 20
  fromEnum TRIANGLE = 48
  fromEnum LPAREN = 38
  fromEnum IF = 4
  fromEnum SIMLE_ESCAPE_SEQUENCE = 65
  fromEnum UCID = 57
  fromEnum COLONHASH = 26
  fromEnum ML_COMMENT = 69
  fromEnum ESCAPE_SEQUENCE = 64
  fromEnum VBAR = 50
  fromEnum RPAREN = 43
  fromEnum SLASH = 46
  fromEnum IN = 15
  fromEnum THEN = 5
  fromEnum COLONEQ = 25
  fromEnum COMMA = 27
  fromEnum HEXADECIMAL_ESCAPE_SEQUENCE = 67
  fromEnum DARROW = 28
  fromEnum SUCC = 11
  fromEnum LEFTARROW = 37
  fromEnum DIGIT = 55
  fromEnum APOSTROPHE = 16
  fromEnum LAMBDA = 9
  fromEnum EQ = 31
  fromEnum DOT = 30
  fromEnum FRACTIONAL_CONSTANT = 59
  fromEnum INTV = 52
  fromEnum EQEQ = 32
  fromEnum DDARROW = 29
  fromEnum PRED = 12
  fromEnum ELSE = 6
  fromEnum HASH = 34
  fromEnum LSQUAREBAR = 40
  fromEnum LCURLY = 35
  fromEnum BANG = 19
  fromEnum RSQUARE = 44
  fromEnum SEMI = 45
  fromEnum TRUE = 7
  fromEnum BARRCURLY = 21
  fromEnum COLON = 23
  fromEnum COLONCOLON = 24
  fromEnum LCID = 51
  fromEnum WS = 68
  fromEnum DIGIT_SEQUENCE = 60
  fromEnum USCORE = 49
  fromEnum RCURLY = 42
  fromEnum ARROW = 18
  fromEnum GT = 33
  fromEnum FALSE = 8
  fromEnum NONZERO_DIGIT = 58
  fromEnum LET = 14
  fromEnum FLOATV = 53
  fromEnum ISZERO = 13

  toEnum 61 = UNIVERSAL_CHARACTER_NAME
  toEnum 62 = S_CHAR_SEQUENCE
  toEnum 41 = LT
  toEnum 47 = STAR
  toEnum 39 = LSQUARE
  toEnum 63 = S_CHAR
  toEnum 66 = OCTAL_ESCAPE_SEQUENCE
  toEnum 54 = STRINGV
  toEnum 36 = LCURLYBAR
  toEnum 17 = DQUOTE
  toEnum 56 = HEXADECIMAL_DIGIT
  toEnum 10 = TIMESFLOAT
  toEnum 22 = BARRSQUARE
  toEnum 20 = BARGT
  toEnum 48 = TRIANGLE
  toEnum 38 = LPAREN
  toEnum 4 = IF
  toEnum 65 = SIMLE_ESCAPE_SEQUENCE
  toEnum 57 = UCID
  toEnum 26 = COLONHASH
  toEnum 69 = ML_COMMENT
  toEnum 64 = ESCAPE_SEQUENCE
  toEnum 50 = VBAR
  toEnum 43 = RPAREN
  toEnum 46 = SLASH
  toEnum 15 = IN
  toEnum 5 = THEN
  toEnum 25 = COLONEQ
  toEnum 27 = COMMA
  toEnum 67 = HEXADECIMAL_ESCAPE_SEQUENCE
  toEnum 28 = DARROW
  toEnum 11 = SUCC
  toEnum 37 = LEFTARROW
  toEnum 55 = DIGIT
  toEnum 16 = APOSTROPHE
  toEnum 9 = LAMBDA
  toEnum 31 = EQ
  toEnum 30 = DOT
  toEnum 59 = FRACTIONAL_CONSTANT
  toEnum 52 = INTV
  toEnum 32 = EQEQ
  toEnum 29 = DDARROW
  toEnum 12 = PRED
  toEnum 6 = ELSE
  toEnum 34 = HASH
  toEnum 40 = LSQUAREBAR
  toEnum 35 = LCURLY
  toEnum 19 = BANG
  toEnum 44 = RSQUARE
  toEnum 45 = SEMI
  toEnum 7 = TRUE
  toEnum 21 = BARRCURLY
  toEnum 23 = COLON
  toEnum 24 = COLONCOLON
  toEnum 51 = LCID
  toEnum 68 = WS
  toEnum 60 = DIGIT_SEQUENCE
  toEnum 49 = USCORE
  toEnum 42 = RCURLY
  toEnum 18 = ARROW
  toEnum 33 = GT
  toEnum 8 = FALSE
  toEnum 58 = NONZERO_DIGIT
  toEnum 14 = LET
  toEnum 53 = FLOATV
  toEnum 13 = ISZERO
  toEnum unmatched = error ("FullUntypedTokens.toEnum: Cannot match " ++ show unmatched)

{-# LINE 19 "FullUntypedInterface.chs" #-}


